# Generated by Django 5.0.6 on 2024-06-21 18:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApi.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 0, 7, 37, 724838)),
        ),
    ]
