# Generated by Django 5.0.6 on 2024-06-21 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0002_alter_booking_name_alter_movie_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 0, 9, 46, 593893)),
        ),
    ]
