# Generated by Django 5.0.6 on 2024-06-21 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0003_alter_movie_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 0, 21, 6, 690525)),
        ),
    ]
