# Generated by Django 5.0.6 on 2024-06-21 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0004_rename_name_booking_movie_alter_movie_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminApi.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 0, 29, 7, 913435)),
        ),
    ]
