# Generated by Django 5.0.6 on 2024-06-23 15:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0005_alter_booking_movie_alter_movie_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApi.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 21, 8, 44, 720853)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time4',
            field=models.CharField(max_length=50),
        ),
    ]
